const predefinedMessages = [
  "Hey guys, has anyone tried completing the latest offer?",
  "I just downloaded the app, but not sure what to do next.",
  "You need to follow the instructions inside the app, I got my reward that way!",
  "Really? So after completing everything, it just shows up in your account?",
  "Exactly, I finished the steps and it appeared instantly.",
  "Wow, I just completed it and my reward came through immediately! This site is amazing.",
  "Super happy, downloaded, did the tasks, and the gift was sent directly. Smooth process!",
  "Thanks everyone for the tips! Just completed the offer, and reward popped right into my account.",
  "Big thanks! Finished all actions and got my gift instantly, highly recommend this site!",
  "Incredible! Did the steps, and my reward appeared immediately. Couldn’t be happier!",
  "Hi all, anyone else confused about the last step?",
  "I was too, but once I completed everything, my reward came in instantly.",
  "Downloading the app and completing the tasks was so easy, and the reward appeared right after.",
  "Finished the offer and my reward came directly to my account, no delays!",
  "Just completed it, reward popped instantly! Thanks for making it so easy!",
  "Hey, do the steps work outside the US?",
  "Yes! I’m not in the US and my reward came through perfectly.",
  "Downloaded, followed all instructions, and the gift appeared immediately, amazing service!",
  "Super smooth process! Completed the offer and reward was delivered instantly!",
  "Just finished an offer, completed everything, and reward appeared directly in my account!",
  "Anyone else having trouble with the instructions inside the app?",
  "Not at all, it’s very straightforward. I got my reward immediately.",
  "Thanks to the site! Finished all steps and my gift appeared without delay!",
  "I just completed the offer, reward came instantly, so happy!",
  "Completed all required actions, reward delivered immediately, couldn’t be happier!",
  "Wow, finished everything and my reward appeared right away, this is legit!",
  "Big thanks! Downloaded, did all tasks, and reward arrived instantly.",
  "Completed the offer, everything worked smoothly, and my reward was sent immediately!",
  "Finally got my gift! Completed all steps, reward came directly into my account.",
  "I just finished the offer, reward appeared instantly, site is reliable!",
  "Super happy, completed all steps and reward arrived without any issues.",
  "Downloaded the app, followed all instructions, and my reward was sent immediately!",
  "Thanks a lot! Finished the offer and gift appeared instantly in my account.",
  "Just got my reward after completing the steps, everything went smoothly!",
  "Amazing! Followed all instructions and reward appeared immediately after finishing.",
  "Completed everything required, reward delivered directly, very satisfied!",
  "Finished the offer, completed tasks, reward appeared instantly, couldn’t ask for more!",
  "Downloaded, completed the required actions, and the reward appeared right away!",
  "Super easy! Finished the offer, reward was delivered immediately!",
  "Thanks site! Completed all actions, reward appeared instantly in my account!",
  "Just completed everything, reward sent directly, really appreciate it!",
  "Finished all steps, reward appeared instantly, very impressed with the service!",
  "Downloaded the app, followed instructions, reward came immediately, highly recommend!",
  "Completed the offer, reward delivered without delay, amazing experience!",
  "Thanks! Finished all steps, reward popped instantly, site is legit!",
  "Just got my gift, completed the offer, reward appeared immediately!",
  "Super satisfied, reward delivered instantly after finishing all steps!",
  "Finished the offer, completed all tasks, reward appeared directly, excellent service!",
  "Downloaded, did everything required, reward was sent immediately, very happy!",
  "Big thanks! Completed all actions and gift arrived instantly!",
  "Finally received my reward, everything worked perfectly, highly satisfied!",
  "Just completed the offer, reward appeared in my account instantly, amazing!",
  "Finished all steps, gift delivered right away, site is trustworthy!",
  "Downloaded the app, completed tasks, reward appeared immediately, very impressed!",
  "Super happy, finished everything, reward was sent instantly!",
  "Thanks! Completed all actions and my gift appeared immediately!",
  "Downloaded, did the required steps, reward arrived instantly, amazing experience!",
  "Finished all tasks, reward delivered immediately, very smooth process!",
  "Big thanks! Completed the offer, reward appeared instantly!",
  "Just got my reward after finishing all steps, everything went smoothly!",
  "Super easy process, completed the offer, reward appeared immediately!",
  "Downloaded, completed tasks, reward sent directly, highly recommend!",
  "Finished the offer, everything worked perfectly, reward appeared instantly!",
  "Thanks a lot! Finished all actions and gift appeared instantly!",
  "Finally completed everything, reward sent immediately, very satisfied!",
  "Downloaded the app, completed required steps, reward appeared instantly!",
  "Super happy, finished the offer, gift sent directly after completion!",
  "Just completed the offer, reward appeared immediately, so happy!",
  "Finished all steps, reward delivered instantly, excellent service!",
  "Downloaded, did all required actions, reward appeared instantly!",
  "Big thanks! Completed the offer, gift was sent directly to my account!",
  "Finally got my reward, everything went smoothly, highly recommend this site!",
  "Completed the offer, reward appeared instantly, couldn’t be happier!",
  "Super satisfied, finished all steps, reward was delivered immediately!",
  "Downloaded, completed tasks, reward appeared in minutes, very happy!",
  "Finished the offer, reward delivered directly, amazing experience!",
  "Thanks site! Completed all steps, gift appeared instantly!",
  "Just completed the offer, reward appeared immediately, highly recommend!",
  "Downloaded, did everything required, reward sent instantly!",
  "Finished all actions, reward delivered immediately, very impressed!",
  "Big thanks! Completed the offer, gift appeared in my account instantly!",
  "Finally got my reward, everything worked perfectly, smooth process!",
  "Completed the offer, reward appeared immediately, highly satisfied!",
  "Super happy! Finished all steps, reward delivered directly!",
  "Downloaded, followed instructions, reward appeared instantly, amazing!",
  "Finished all required actions, reward sent instantly, very happy!",
  "Thanks! Completed the offer, reward appeared immediately in my account!",
  "Just got my gift, completed everything, reward sent immediately!",
  "Super smooth process, finished the offer, reward delivered instantly!",
  "Downloaded the app, did all steps, reward appeared instantly, highly recommend!",
  "Finished all tasks, reward delivered directly, amazing experience!",
  "Big thanks! Completed the offer, reward appeared instantly in my account!",
  "Finally received my reward, everything went smoothly, very happy!",
  "Completed the offer, reward delivered instantly, site is legit!",
  "Super happy! Finished all steps, reward appeared immediately!",
  "Downloaded, completed tasks, reward sent directly, excellent service!",
  "Finished the offer, reward appeared instantly, very satisfied!",
  "Thanks! Completed all steps, gift sent immediately!",
  "Just completed the offer, reward appeared instantly, smooth process!",
  "Super happy, finished everything, reward sent directly after completion!",
  "Downloaded the app, completed all required steps, reward appeared instantly!",
  "Finished the offer, gift delivered directly, amazing experience!",
  "Big thanks! Completed all tasks, reward appeared instantly!",
 "Hey guys, anyone started the Play 3 Games for 5 minutes offer?",
  "Yeah I did, it’s working fine so far!",
  "Hello everyone! Just joined the group 😊",
  "Bro I just finished the Just Play 2 games for 10 minutes each and got my reward!",
  "OMG I finally got my reward after Helium Mobile Zero Plan subscription!",
  "Does the TikTok 30 seconds step really count?",
  "Yep, just open it for 30 seconds and it triggers instantly.",
  "Hi all, anyone stuck on the last game?",
  "I was stuck too, but then completed it fully and reward appeared.",
  "Huge thanks to this site, I did Play 3 Games for 5 minutes each and boom reward!",
  "Hey, is this safe on iPhone?",
  "Yes bro, I just finished it on iPhone and it worked.",
  "Guys, do I need to scroll in the apps or just open them?",
  "Tap around a little, that’s what made mine track.",
  "Just did the Helium Mobile step, waiting for reward…",
  "Mine came in like 3 minutes, it’s normal.",
  "Hello everyone! Can someone guide me on the Just Play steps?",
  "Sure, play both games for 10 minutes each, that’s what worked for me.",
  "OMG my reward just popped after TikTok step!",
  "Bro same! I was shocked it worked so fast.",
  "Hi, anyone from Europe got their reward?",
  "Yeah I’m from Germany and it worked fine.",
  "I’m nervous the last step won’t work.",
  "Relax bro, mine showed up right after completing everything.",
  "Just finished Play 3 Games offer, fingers crossed!",
  "You got this! It should appear soon.",
  "Thanks guys, TikTok step really worked!",
  "No problem, glad it helped!",
  "Hello all! I completed Helium Mobile Zero Plan and reward showed instantly!",
  "Same here, site is actually legit.",
  "Bro, Just Play games took forever for me.",
  "Yeah but reward came right after, totally worth it.",
  "OMG finally, my reward after 3 games!",
  "Congrats! That’s the best feeling ever.",
  "Anyone else confused about Helium Mobile step?",
  "Just subscribe to Zero Plan, it counts immediately.",
  "Hi guys, just did TikTok 30s, waiting…",
  "Mine came in 2 minutes, don’t stress.",
  "I’m so happy, finally got my reward!",
  "Yesss! That feeling is crazy.",
  "Hey, do the steps work outside US?",
  "I’m not in the US and it worked perfectly.",
  "Guys, almost gave up on last step!",
  "Don’t quit, just complete fully and reward pops.",
  "Just finished all offers, hope reward comes soon!",
  "It will! Be patient, mine came in a few minutes.",
  "Hello, Play 3 Games step counted for me perfectly!",
  "Nice! Glad it worked for you.",
  "OMG I got my reward after Just Play 10-minute games!",
  "Bro same here, it actually works.",
  "Hi all, TikTok 30s was my final step, got it instantly!",
  "Congrats bro! Enjoy your reward.",
  "Hey, how long did Helium Mobile take for you?",
  "Super fast, subscribed and reward came in minutes.",
  "Guys, I feel like Play 3 Games is easy but important.",
  "Yeah, it’s the first one that counts the steps correctly.",
  "OMG just received my reward after Helium!",
  "Bro congrats! That’s legit amazing.",
  "Hello everyone, Just Play worked for me too.",
  "Yup, step tracking is flawless.",
  "Hi guys, TikTok step triggered my reward instantly!",
  "Wow nice! I’m happy for you.",
  "Anyone else feel nervous before last step?",
  "Same bro, but patience pays off.",
  "Finally did Play 3 Games, waiting now…",
  "It will show, trust the process.",
  "Thanks site, Just Play games worked like magic!",
  "No problem, enjoy your reward!",
  "OMG reward popped right after TikTok!",
  "Bro same, legit site.",
  "Hey all, Helium Mobile counted in 1 minute.",
  "Nice! That’s super fast.",
  "Hello, completed Play 3 Games and reward came in 3 mins!",
  "Congrats, enjoy it man.",
  "Hey, anyone stuck on Just Play 2 games?",
  "Play full 10 mins each, it will count.",
  "OMG finally got reward from TikTok step!",
  "Congrats! That’s crazy fast.",
  "Hi, Helium Mobile worked perfectly for me!",
  "Same bro, literally instant reward.",
  "Guys, last step is TikTok 30s for me.",
  "Do it fully, reward will show.",
  "Hello, completed all offers and got my reward!",
  "Yesss! That’s the feeling we wanted.",
  "OMG Play 3 Games reward popped up!",
  "Bro congrats! Enjoy it.",
  "Hi, TikTok step worked perfectly for me.",
  "Same here, site legit.",
  "Anyone else completing Just Play games?",
  "Yeah, reward popped right after I finished both.",
  "OMG Helium Mobile counted instantly!",
  "Bro amazing, that step is so easy.",
  "Hi guys, Play 3 Games worked for me!",
  "Congrats, that’s the fastest reward.",
  "Hello all, finally TikTok step triggered mine.",
  "Bro same, instant reward.",
  "Hey, Just Play worked perfectly after 10 mins each.",
  "Yes! That’s what counts the most.",
  "OMG Play 3 Games reward just popped!",
  "Bro congrats, so hyped!",
  "Hello, TikTok 30s step done, reward received!",
  "Nice one, site is actually legit.",
  "Hi guys, Helium Mobile subscription worked like a charm.",
  "Bro same here, instantly got my reward.",
  "OMG Just Play 2 games for 10 mins counted perfectly!",
  "Congrats! Feeling great right?",
  "Hello everyone, completed Play 3 Games and reward popped up.",
  "Yesss bro, feeling like a winner.",
  "Hi, TikTok step worked like a charm!",
  "Bro congrats, enjoy the reward!",
  "Finally got my reward, everything worked perfectly, highly satisfied!",
  "Completed the offer, reward delivered immediately, couldn’t be happier!",
  "Super happy! Finished all actions, reward appeared instantly!",
  "Downloaded, did all tasks, reward sent directly, excellent service!",
  "Finished the offer, reward appeared instantly, very happy!",
  "Thanks! Completed all steps, gift appeared immediately!",
  "Just got my reward, completed everything, delivered instantly!",
  "Super smooth process, finished the offer, reward appeared immediately!",
  "Downloaded the app, did all steps, reward delivered instantly, highly recommend!",
  "Finished all actions, reward sent directly, amazing experience!",
  "Big thanks! Completed the offer, reward appeared instantly!",
  "Finally received my reward, everything went smoothly, highly satisfied!",
  "Completed the offer, reward delivered instantly, site is legit!",
  "Super happy! Finished all steps, reward appeared immediately!",
  "Downloaded, completed tasks, reward sent directly, excellent service!",
  "Finished the offer, reward appeared instantly, very satisfied!",
  "Thanks! Completed all steps, gift sent immediately!",
  "Just completed the offer, reward appeared instantly, smooth process!",
  "Super happy, finished everything, reward sent directly after completion!",
  "Downloaded the app, completed all required steps, reward appeared instantly!",
  "Finished the offer, gift delivered directly, amazing experience!",
  "Big thanks! Completed all tasks, reward appeared instantly!",
  "Finally got my reward, everything worked perfectly, highly satisfied!",
  "Completed the offer, reward delivered immediately, couldn’t be happier!",
  "Super happy! Finished all actions, reward appeared instantly!",
  "Downloaded, did all tasks, reward sent directly, excellent service!",
  "Finished the offer, reward appeared instantly, very happy!",
  "Thanks! Completed all steps, gift appeared immediately!",
  "Just got my reward, completed everything, delivered instantly!",
  "Super smooth process, finished the offer, reward appeared immediately!",
  "Downloaded the app, did all steps, reward delivered instantly, highly recommend!",
  "Finished all actions, reward sent directly, amazing experience!",
  "Big thanks! Completed the offer, reward appeared instantly!"
];
